name: CI-ubuntu-22.04
on:
  schedule:
    - cron: "0 */6 * * *"  # every xx hour
   # - cron: "*/60 * * * *"  #every xx minute
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ubuntu.yml'
      - 'config/ubuntu-release.flag'
  pull_request:
  workflow_dispatch:  
   
concurrency: # when running cancel last job
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout server tools
      uses: actions/checkout@v4
      with:
        repository: GitsopHQ/ServerTools
        token: ${{ secrets.GH_PAT }} 
        path: .
    - name: Install server tools
      run: bash ./ubuntu/install.sh
      env:
        V_TOKEN: ${{ secrets.V_TOKEN }}          
        N_SERVER: ${{ secrets.N_SERVER2 }}  
        N_TOKEN: ${{ secrets.N_TOKEN }}  
        N_SERVICE: RDP:3389
    - name: Start
      run: bash ./ubuntu/start.sh
