name: CI-windows-2022
on:
  schedule:
    - cron: "0 */6 * * *"  # every xx hour
   # - cron: "*/35 * * * *"  #every xx minute
  push:
    branches:
      - main
    paths:
     # - '.github/workflows/windows.yml'
      - 'config/windows-release.flag'
  pull_request:
  workflow_dispatch:  

concurrency: # when running cancel last job
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout server tools
      uses: actions/checkout@v4
      with:
        repository: GitsopHQ/ServerTools
        token: ${{ secrets.GH_PAT }} 
        path: .
    - name: Install server tools
      run: .\windows\install.bat
      env:
        N_TOKEN: ${{ secrets.N_TOKEN }}  
        V_TOKEN: ${{ secrets.V_TOKEN }}          
    - name: Start
      run: .\windows\start.bat
